#!/bin/bash

sudo apt install curl vim neovim -y
echo "alias vim=nvim" > ~/.zshrc

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "\" PROPERTIES
set nocompatible
\" allow recursive file search from current directory
set path+=./**
\" display all matching files when we tab complete
set wildmenu

syntax on
filetype plugin on
set nu
set splitbelow

filetype plugin indent on
\" show existing tab with 4 spaces width
set tabstop=4
\" when indenting with '>', use 4 spaces width
set shiftwidth=4
\" On pressing tab, insert 4 spaces
set expandtab

\" PULUGINS (vim-plug - https://github.com/junegunn/vim-plug)
call plug#begin()

\" conquer of completion - https://github.com/neoclide/coc.nvim
Plug 'neoclide/coc.nvim', {'branch': 'release'}

\" nerdtree - https://github.com/preservim/nerdtree
Plug 'preservim/nerdtree'

call plug#end()

\" KEY BINDINGS
\" save on CTRL s (for normal and insert mode)
nnoremap <C-s> :w<CR>
inoremap <C-s> <ESC>:w<CR>a
\" copy visual selection to system clipboard
vnoremap <C-c> \"+y<CR>

\" close all on CTRL q (for normal and insert mode)
nnoremap <C-q> :qa<CR>
inoremap <C-q> <ESC>:qa<CR>
\" close selected frame on CTRL d (for normal and insert mode)
nnoremap <C-d> :q<CR>
inoremap <C-d> <ESC>:q<CR>

\" toggle nerd tree CTRL e (plugin required)
nnoremap <C-e> :NERDTreeToggle<CR>
let g:netrw_browse_split=4  \" open in prior window

\" show terminal CTRL t
nnoremap <C-t> :terminal<CR>

\" SNIPPETS
\" nnoremap ,html :-1read $HOME/.vim/.skeleton.html<CR>3jwf>a
" > ~/.vimrc


mkdir -p ~/.config/nvm/
echo "source ~/.vimrc" > ~/.config/nvm/init.nvm

mkdir -p ~/.config/coc/
echo "{
    \"suggest.enablePreselect\": true,
    \"suggest.noselect\": false
}" > ~/.config/coc/coc-settings.json

vim +"PlugInstall" +qa
source ~/.zshrc
